# Generated by Django 3.2.11 on 2024-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner_image',
            field=models.ImageField(default='/some_screenshot.png', upload_to='', verbose_name='banner image'),
        ),
    ]
